import os  # Standard library for file system operations (creating directories, checking paths)
import cv2  # OpenCV library for image processing (loading, resizing, applying colormaps)
import torch  # PyTorch library for deep learning and tensor operations
import numpy as np  # Library for numerical arrays and matrix manipulation
import faiss  # Facebook AI Similarity Search, used for the Nearest Neighbor search (Memory Bank)
from PIL import Image  # Python Imaging Library for loading images in a format compatible with Torchvision
from pathlib import Path  # Object-oriented filesystem paths (easier to work with than raw strings)
from tqdm import tqdm  # Library to display progress bars for loops
import matplotlib.pyplot as plt  # Library for plotting the final visualization figures
import torchvision.transforms as T  # PyTorch transforms for image preprocessing (resize, normalize)
from scipy.ndimage import gaussian_filter  # Function for applying Gaussian Blur to smooth the heatmaps

# --- Import your project modules ---
from src.models import get_feature_extractor  # Imports the custom MobileNetV3 model wrapper

# --- Configuration ---
RESOLUTION = 128  # Sets input resolution to 128x128. This is the key optimization for speed (<100ms latency)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")  # Auto-selects GPU for fast inference
GAUSSIAN_SIGMA = 4.0  # Controls the smoothness of the heatmap. Higher value = smoother, less pixelated
IMAGENET_NORM = T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # Standard ImageNet normalization stats required for pre-trained MobileNet

# List of all MVTec AD Categories to iterate through
MVTEC_CATEGORIES = [
    'bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut', 
    'leather', 'metal_nut', 'pill', 'screw', 'tile', 'toothbrush', 
    'transistor', 'wood', 'zipper'
]

def load_memory_bank(category):
    """Loads the pre-computed FAISS index for a specific category."""
    # Constructs the path to the .index file generated by the build script
    bank_path = f"models/{category}_patch_memory_bank.index"
    
    # Checks if the file exists to prevent crashing if a category was skipped during training
    if not os.path.exists(bank_path):
        print(f"[SKIP] Memory bank not found for '{category}': {bank_path}")
        return None  # Returns None so the main loop knows to skip this category
        
    return faiss.read_index(bank_path)  # Loads the FAISS index from disk into memory

def generate_heatmap(orig_image_path, error_map, output_path, title_text):
    """
    Creates a professional Heatmap Overlay and saves it with a TITLE.
    """
    # 1. Load and Resize Original Image
    img = cv2.imread(str(orig_image_path))  # Reads the image using OpenCV
    if img is None: return  # Safety check if image read fails

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Converts BGR (OpenCV default) to RGB (Matplotlib format)
    img = cv2.resize(img, (RESOLUTION, RESOLUTION))  # Resizes image to match the model input size (128x128)

    # 2. Normalize Error Map (0 to 255)
    # Scales the raw anomaly distances to a 0-255 range so they can be displayed as an image
    norm_map = (error_map - error_map.min()) / (error_map.max() - error_map.min() + 1e-8)
    norm_map = (norm_map * 255).astype(np.uint8)  # Converts float scores to 8-bit integers

    # 3. Apply Jet Colormap
    # Applies a color map where Blue = Low Anomaly (Good) and Red = High Anomaly (Defect)
    heatmap = cv2.applyColorMap(norm_map, cv2.COLORMAP_JET)
    heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)  # Converts heatmap to RGB

    # 4. Create Overlay
    alpha = 0.4  # Sets transparency factor (40% heatmap, 60% original image)
    overlay = cv2.addWeighted(img, 1 - alpha, heatmap, alpha, 0)  # Blends the original image and heatmap

    # 5. Save Side-by-Side (Input | Heatmap | Overlay)
    # Creates a figure with 1 row and 3 columns
    fig, axes = plt.subplots(1, 3, figsize=(12, 5)) 
    
    # Add the Category and Defect Name at the top of the entire figure
    fig.suptitle(title_text, fontsize=16, fontweight='bold')
    
    # Plot 1: Original Image
    axes[0].imshow(img); axes[0].axis('off'); axes[0].set_title("Input")
    
    # Plot 2: The raw heatmap colors
    axes[1].imshow(heatmap); axes[1].axis('off'); axes[1].set_title("Heatmap")
    
    # Plot 3: The overlay showing localization context
    axes[2].imshow(overlay); axes[2].axis('off'); axes[2].set_title("Overlay")
    
    plt.tight_layout()  # Adjusts spacing to prevent overlap
    plt.savefig(output_path)  # Saves the figure to disk
    plt.close()  # Closes the figure to free up RAM

def process_category(category, model):
    print(f"\n🚀 Processing category: '{category}'...")
    
    # Load the specific memory bank for this category (e.g., 'bottle')
    index = load_memory_bank(category)
    if index is None: return  # Skip if trained model doesn't exist
    
    raw_feature_dim = 176  # MobileNet output dimension (concatenated layers 1+2+3)
    
    # Define paths for test images and output
    test_dir = Path("data/mvtec_ad") / category / "test"
    output_dir = Path("results/heatmaps") / category
    os.makedirs(output_dir, exist_ok=True)  # Create output folder
    
    # Define the image preprocessing pipeline (Must match training!)
    test_transform = T.Compose([
        T.Resize((RESOLUTION, RESOLUTION)),  # Resize to 128x128
        T.ToTensor(),  # Convert to PyTorch Tensor
        IMAGENET_NORM  # Apply ImageNet normalization
    ])
    
    # Iterate through all subfolders (defect types like 'broken_large', 'good', etc.)
    for defect_type in sorted(test_dir.iterdir()):
        if not defect_type.is_dir(): continue
        
        # Create a specific folder for this defect type in results
        save_dir = output_dir / defect_type.name
        os.makedirs(save_dir, exist_ok=True)

        # Get all image files in this defect folder
        image_files = sorted(defect_type.glob("*.png"))
        if not image_files: continue

        # Loop through each image with a progress bar
        for img_path in tqdm(image_files, desc=f"  > {defect_type.name}"):
            
            # --- 1. Inference ---
            image = Image.open(img_path).convert("RGB")  # Load image
            x = test_transform(image).unsqueeze(0).to(DEVICE)  # Preprocess and add batch dimension [1, 3, 128, 128]
            
            with torch.no_grad():  # Disable gradients for inference speed
                patch_features = model(x)  # Extract features from MobileNet backbone
                
                # Get spatial dimensions of the feature map
                H, W = patch_features.shape[2:] 
                
                # Reshape features to [Total_Patches, Feature_Dim] for FAISS
                patch_vectors = patch_features.permute(0, 2, 3, 1).reshape(H * W, raw_feature_dim)
                patch_vectors_np = patch_vectors.cpu().numpy()  # Convert to NumPy for FAISS

            # Nearest Neighbor Search: Find the distance to the closest 'normal' patch in memory
            # D = Distances (Anomaly Scores), I = Indices (not used here)
            D, I = index.search(patch_vectors_np, 1) 
            
            # --- 2. Map Generation ---
            # Reshape the flat distances back to a 2D grid [H, W]
            anomaly_map_hw = D.reshape(H, W)
            
            # Upsample the small feature map (e.g., 8x8) back to input size (128x128)
            # Bilinear interpolation creates a smooth transition between patches
            anomaly_map_full = T.Resize(
                (RESOLUTION, RESOLUTION), 
                interpolation=T.InterpolationMode.BILINEAR,
                antialias=True
            )(torch.tensor(anomaly_map_hw).unsqueeze(0).unsqueeze(0)).squeeze().numpy()
            
            # Apply Gaussian Blur to remove grid artifacts and make the heatmap look organic
            error_map = gaussian_filter(anomaly_map_full, sigma=GAUSSIAN_SIGMA)
            
            # --- 3. Save Heatmap with Title ---
            save_path = save_dir / f"heatmap_{img_path.name}"
            
            # Create a descriptive title string for the chart
            title_str = f"Category: {category} | Defect: {defect_type.name}"
            
            # Call the visualization function
            generate_heatmap(img_path, error_map, str(save_path), title_str)

if __name__ == "__main__":
    print("Loading MobileNetV3 backbone...")
    # Initialize the shared feature extractor (same model used for all categories)
    shared_model = get_feature_extractor().to(DEVICE)
    shared_model.eval()  # Set to evaluation mode (freezes BatchNorm stats)

    # Loop through every category in the MVTec dataset
    for cat in MVTEC_CATEGORIES:
        process_category(cat, shared_model)
        
    print("\nDONE. All heatmaps generated in 'results/heatmaps/'")
